### PR TITLE
fixed effects #29

### PR DESCRIPTION
**Pull request by harshsbhandari**
@ojasaklechayt Fixed the color of sidebar as you suggested and added hover effect too, used the green color used in the Create Project button in the header
Screenshot (166)

### CODE REVIEW

**Comment by ojasaklechayt** [comment]
image

When I am hovering, I am getting two green hover buttons. Can you please try improving this

**Comment by harshsbhandari** [comment]
> image
> 
> When I am hovering, I am getting two green hover buttons. Can you please try improving this

You are on dashboard page, that's why it's green and you are hovering on projects page that's why it is becoming green. Should I change the selected button color to some other color ?

**Comment by ojasaklechayt** [comment]
> > image
> > When I am hovering, I am getting two green hover buttons. Can you please try improving this
> 
> You are on dashboard page, that's why it's green and you are hovering on projects page that's why it is becoming green. Should I change the selected button color to some other color ?

Yeah that would be better, like on hover, some other color

**Comment by harshsbhandari** [comment]
> > > image
> > > When I am hovering, I am getting two green hover buttons. Can you please try improving this
> > 
> > 
> > You are on dashboard page, that's why it's green and you are hovering on projects page that's why it is becoming green. Should I change the selected button color to some other color ?
> 
> Yeah that would be better, like on hover, some other color

@ojasaklechayt added diff color on hover, please check that out. Also please add hacktober tags to this

**Pull request merged**
